# Gaussian Elimination

In [6]:
import numpy as np

This function performs LU decomposition of given matrix A.

In [7]:
def LU(A):
    n = A.shape[0]
    L = np.identity(n)
    U = np.array(A)
    for i in range(n-1):
        L[i+1:n,i] = U[i+1:n,i]/U[i,i]
        for j in range(i+1,n):
            U[j,i+1:n] = U[j,i+1:n] - L[j,i] * U[i,i+1:n]
        U[i+1:n,i] = 0.0
    return L,U

This performs performs solution of
$$
LUx=b
$$
in two steps. In first step, solve
$$
Ly = b
$$
using
$$
y_i = \frac{1}{L_{ii}} \left[b_i - \sum_{j=0}^{i-1} L_{ij} y_j\right], \qquad i=0,1,\ldots,n-1
$$
Note that $L_{ii}=1$, so we can drop the division step. In second step, solve
$$
Ux = y
$$
using
$$
x_i = \frac{1}{U_{ii}}\left[y_i - \sum_{j=i+1}^{n-1} U_{ij} x_j \right], \qquad i=n-1,n-2,\ldots,0
$$

In [8]:
def LUSolve(L,U,b):
    n = L.shape[0]
    # solve Ly = b
    y = np.empty_like(b)
    for i in range(n):
        y[i] = b[i] - L[i,0:i].dot(y[0:i])
    # solve Ux = y
    x = np.empty_like(b)
    for i in range(n-1,-1,-1):
        x[i] = (y[i] - U[i,i+1:n].dot(x[i+1:n]))/U[i,i]
    return x

Now we test the above function for LU decomposition. We initialize $A$ to a random matrix and compute its LU decomposition.

In [9]:
n = 3
A = np.random.rand(n,n)
L,U = LU(A)
print "A = "; print A
print "L = "; print L
print "U = "; print U
print A - L.dot(U)

A = 
[[ 0.91130171  0.8869563   0.10036248]
 [ 0.69418229  0.63777574  0.64138565]
 [ 0.44829369  0.33627297  0.97627635]]
L = 
[[ 1.          0.          0.        ]
 [ 0.76174804  1.          0.        ]
 [ 0.49192675  2.64238394  1.        ]]
U = 
[[ 0.91130171  0.8869563   0.10036248]
 [ 0.         -0.03786148  0.56493473]
 [ 0.          0.         -0.56586909]]
[[  0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00  -1.11022302e-16]]


Solve the linear system.

In [10]:
b = np.random.rand(n)
x = LUSolve(L,U,b)
print A.dot(x) - b

[  1.33226763e-15  -1.88737914e-15   1.11022302e-16]
