# Gaussian Elimination

In [10]:
import numpy as np

This function performs LU decomposition of given matrix A.

In [11]:
def LU(A):
    n = A.shape[0]
    L = np.zeros((n,n))
    U = np.array(A)
    for i in range(n-1):
        L[i,i] = 1.0
        L[i+1:n,i] = U[i+1:n,i]/U[i,i]
        for j in range(i+1,n):
            U[j,i+1:n] = U[j,i+1:n] - L[j,i] * U[i,i+1:n]
        U[i+1:n,i] = 0.0
    L[n-1,n-1] = 1.0
    return L,U

This performs performs solution of
$$
LUx=b
$$
in two steps. In first step, solve
$$
Ly = b
$$
using
$$
y_i = \frac{1}{L_{ii}} \left[b_i - \sum_{j=0}^{i-1} L_{ij} y_j\right], \qquad i=0,1,\ldots,n-1
$$
In second step, solve
$$
Ux = y
$$
using
$$
x_i = \frac{1}{U_{ii}}\left[y_i - \sum_{j=i+1}^{n-1} U_{ij} x_j \right], \qquad i=n-1,n-2,\ldots,0
$$

In [12]:
def LUSolve(L,U,b):
    n = L.shape[0]
    # solve Ly = b
    y = 0*b
    for i in range(n):
        y[i] = (b[i] - L[i,0:i].dot(y[0:i]))/L[i,i]
    # solve Ux = y
    x = 0*b
    for i in range(n-1,-1,-1):
        x[i] = (y[i] - U[i,i+1:n].dot(x[i+1:n]))/U[i,i]
    return x

Now we test the above function for LU decomposition. We initialize $A$ to a random matrix and compute its LU decomposition.

In [13]:
n = 3
A = np.random.rand(n,n)
L,U = LU(A)
print "A = "; print A
print "L = "; print L
print "U = "; print U
print A - L.dot(U)

A = 
[[ 0.55198372  0.82418968  0.92812346]
 [ 0.72187729  0.42110018  0.91918334]
 [ 0.85796063  0.50663298  0.77303437]]
L = 
[[ 1.          0.          0.        ]
 [ 1.30778728  1.          0.        ]
 [ 1.55432234  1.1791492   1.        ]]
U = 
[[ 0.55198372  0.82418968  0.92812346]
 [ 0.         -0.6567646  -0.29460472]
 [ 0.          0.         -0.32218574]]
[[  0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   1.11022302e-16   1.11022302e-16]]


Solve the linear system.

In [14]:
b = np.random.rand(n)
x = LUSolve(L,U,b)
print A.dot(x) - b

[  1.38777878e-16   3.88578059e-16   4.44089210e-16]
