# Gaussian Elimination

In [1]:
import numpy as np

This function performs LU decomposition of given matrix A.

In [2]:
def LU(A):
    n = A.shape[0]
    L = np.zeros((n,n))
    U = np.array(A)
    for i in range(n-1):
        L[i,i] = 1.0
        L[i+1:n,i] = U[i+1:n,i]/U[i,i]
        for j in range(i+1,n):
            U[j,i+1:n] = U[j,i+1:n] - L[j,i] * U[i,i+1:n]
        U[i+1:n,i] = 0.0
    L[n-1,n-1] = 1.0
    return L,U

This performs performs solution of
$$
LUx=b
$$
in two steps. In first step, solve
$$
Ly = b
$$
In second step, solve
$$
Ux = y
$$

In [3]:
def LUSolve(L,U,b):
    n = L.shape[0]
    # solve Ly = b
    y = 0*b
    for i in range(n):
        y[i] = (b[i] - L[i,0:i].dot(y[0:i]))/L[i,i]
    # solve Ux = y
    x = 0*b
    for i in range(n-1,-1,-1):
        x[i] = (y[i] - U[i,i+1:n].dot(x[i+1:n]))/U[i,i]
    return x

Now we test the above function for LU decomposition.

In [4]:
n = 3
A = np.random.rand(n,n)
L,U = LU(A)
print A
print L
print U
print A - L.dot(U)

[[ 0.3724645   0.15326785  0.73766056]
 [ 0.96120642  0.73729898  0.7062711 ]
 [ 0.45681567  0.845315    0.53508613]]
[[ 1.          0.          0.        ]
 [ 2.58066585  1.          0.        ]
 [ 1.22646769  1.9233545   1.        ]]
[[ 0.3724645   0.15326785  0.73766056]
 [ 0.          0.34176587 -1.19738432]
 [ 0.          0.          1.93336381]]
[[  0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.11022302e-16   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   1.11022302e-16   0.00000000e+00]]


Solve the linear system.

In [5]:
b = np.random.rand(n)
x = LUSolve(L,U,b)
print A.dot(x) - b

[  0.00000000e+00   1.11022302e-16   1.11022302e-16]
