# Gaussian Elimination with row pivoting

In [1]:
import numpy as np

This function performs LU decomposition of given matrix A with pivoting to obtain
$$
PA = LU
$$
where $P$ is a permutation matrix. Here we dont store $P$ as a matrix, but only as a vector.

In [2]:
def LU(A):
    n = A.shape[0]
    L = np.identity(n)
    P = np.arange(n,dtype=int) # Permutation matrix
    U = np.array(A)
    for k in range(n-1):
        i = np.argmax(abs(U[k:n,k]))
        i = i+k
        U[[k,i],k:n] = U[[i,k],k:n] # swap row i and k
        L[[k,i],0:k] = L[[i,k],0:k] # swap row i and k
        P[[k,i]] = P[[i,k]]         # swap row i and k
        for j in range(k+1,n):
            L[j,k] = U[j,k]/U[k,k]
            U[j,k:n] = U[j,k:n] - L[j,k]*U[k,k:n]
    return L,U,P

This performs solution of
$$
LUx = Pb
$$
in two steps. In first step, solve
$$
Ly = Pb
$$
In second step, solve
$$
Ux = y
$$

In [3]:
def LUSolve(L,U,P,b):
    n = L.shape[0]
    # solve Ly = Pb
    pb = b[P]
    y = 0.0*pb
    for i in range(n):
        y[i] = (pb[i] - L[i,0:i].dot(y[0:i]))/L[i,i]
    #solve Ux = y
    x = 0.0*pb
    for i in range(n-1,-1,-1):
        x[i] = (y[i] - U[i,i+1:n].dot(x[i+1:n]))/U[i,i]
    return x

Now we test the above function for LU decomposition.

In [4]:
n = 3
A = np.random.rand(n,n)
L,U,P = LU(A)
print A
print L
print U
print P
print P.dot(A) - L.dot(U)

[[ 0.59128337  0.4157061   0.63402054]
 [ 0.5668906   0.47389968  0.89439016]
 [ 0.40401103  0.73216683  0.4282355 ]]
[[ 1.          0.          0.        ]
 [ 0.68327819  1.          0.        ]
 [ 0.95874607  0.16813004  1.        ]]
[[ 0.59128337  0.4157061   0.63402054]
 [ 0.          0.44812391 -0.0049769 ]
 [ 0.          0.          0.28736223]]
[0 2 1]
[[ 0.94650887  1.26426009  1.58299528]
 [ 1.1337812   0.94779936  1.78878032]
 [ 0.97090163  1.20606651  1.32262566]]


Solve the linear system.

In [5]:
b = np.random.rand(n)
x = LUSolve(L,U,P,b)
print A.dot(x) - b

[  0.00000000e+00  -2.22044605e-16  -5.55111512e-17]
